### ISSUE TITLE
Draft a logging infrastructure

### ISSUE THREAD

**Issue by bartjkdp** [Project-Meerkat/backend2#14]
We would like to have a logging infrastructure for:

- Basic user actions (registration, login, logout)
- Group and object actions (CRUD)

**Comment by Phanoix** [comment]
What kind of logging do you have in mind? Regular log file / stdout > fluentd or a system log table similar to elgg? With full post / object versioning I think anything beyond a login log would be redundant as part of the system.

**Comment by bartjkdp** [comment]
Django-revisions for now has all the logging we need.
