### ISSUE TITLE
Draft a notification infrastructure

### ISSUE THREAD

**Issue by bartjkdp** [Project-Meerkat/backend2#19]
As we are building social tooling, we should think about notifications extensively as well. Some basic requirements:

- Aggregation of actions on same objects, like multiple replies to a discussion.
- Aggregation of activities, combine multiple activities in one e-mail.
- Configurable channels (web application with websockets, browser push API, app, e-mail).
- Do-not-disturb mode.
- Send notification only once. So do not bother the user with an e-mail when the user is online.

**Comment by lucbelliveau** [comment]
https://github.com/pinax/pinax-notifications
https://github.com/django-notifications/django-notifications

**Comment by bartjkdp** [comment]
This could work as well: https://github.com/tschellenbach/Stream-Framework

**Comment by lucbelliveau** [comment]
a few other things

https://onesignal.com/
https://github.com/appscode/go-notify
