### ISSUE TITLE
Draft a first object-versioning implementation

### ISSUE THREAD

**Issue by bartjkdp** [Project-Meerkat/backend2#9]

**Comment by AadSchippers** [comment]
We might want to look at [django-simple-history](https://django-simple-history.readthedocs.io/en/latest/index.html).

**Comment by lucbelliveau** [comment]
My quick idea was to somehow merge git versioning with models... but only if there is some functionality needed that doesn't exist already elsewhere... like in django-simple-history mentioned by @AadSchippers.

**Comment by lucbelliveau** [comment]
decided to go with `django-reversion`, mostly because of this: https://djangopackages.org/grids/g/versioning/
